/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qiufg_hotfix_BugFixManager */

#ifndef _Included_com_qiufg_hotfix_BugFixManager
#define _Included_com_qiufg_hotfix_BugFixManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qiufg_hotfix_BugFixManager
 * Method:    replaceArt
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_com_qiufg_hotfix_BugFixManager_replaceArt
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
